springboot:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-schema-name: authorization
    token-type: Bearer
    access-token-expiry: 7200000
    refresj-token-expiry: 1296000000

# DB \uC811\uC18D \uC815\uBCF4
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/greengram3
    username: root
    password: green502
    # 도커

# MYBATIS \uC0C8\uD305
mybatis:
  mapper-locations: mappers/**/*.xml

# SWAGGER \uC0C8\uD305
springdoc:
  swagger-ui:
    path: /swagger.html

fcm:
  certification: serviceAccountKey.json